// <auto-generated />
namespace PetBoardingApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mySql : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mySql));
        
        string IMigrationMetadata.Id
        {
            get { return "202403222219157_mySql"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
